[tool.pylint."messages control"]
disable = ["trailing-whitespace", "trailing-newlines"]

[tool.flake8]
ignore = ["W291", "W293"]

[tool.ruff]
# Disable trailing whitespace warnings
ignore = ["W291", "W293"]

[tool.ruff.lint]
# Disable trailing whitespace checks
ignore = ["W291", "W293"]

